server:
  port: 8080
  servlet.context-path: /undertow1.4.22-demo
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crm?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  spring:
    resources:
      static-locations: static/
mybatis:
  mapper-locations: classpath*:config/mybatis/*.xml
  type-aliases-package: com.vigorsky.origin.crm.entity
  configuration:
    map-underscore-to-camel-case: true